# Generated by Django 4.0.5 on 2022-06-06 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='AccountType',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='Phone_number',
        ),
        migrations.DeleteModel(
            name='ModelLeesee',
        ),
    ]
